### ISSUE TITLE
"Error: Get https://xxx.xxx.xxx.xxx/apis/apps/v1beta1: error executing access token command "/use/local/bin/gcloud ": exit status 2"

### ISSUE THREAD

**Issue by tomwilkie** [ksonnet/kubecfg#45]
I'm using GKE, and as such my k8s credentials are like this:

```yaml
- name: foo
  user:
    auth-provider:
      config:
        access-token: REDACTED
        cmd-args: config config-helper --format=json
        cmd-path: /usr/local/bin/gcloud
        expiry: 2017-06-29T16:17:45Z
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```

When I run `kubecfg update ...` I get the error `Error: Get https://xxx.xxx.xxx.xxx/apis/apps/v1beta1: error executing access token command "/usr/local/bin/gcloud ": exit status 2`.  If I run `kubectl get pods` it works, and subsequent `kubecfg update` commands work, until the token expires I guess.
